### ISSUE TITLE
[Bug] 下载完包后的警告和资源引用报错

### ISSUE THREAD

**Issue by clear-zhao** [iNKORE-NET/UI.WPF.Modern#100]
**Describe the bug**
1. NU1701	已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1”而不是项目目标框架“net8.0-windows7.0”还原包“iNKORE.UI.WPF.Modern 0.9.30”。此包可能与项目不完全兼容。	
2. 错误	XDG0003	Requested value 'TopLeftValue' was not found.	

**Screenshots**
1. ![image](https://github.com/user-attachments/assets/930a556f-bc3e-4646-8c0e-b5a35111432b)

2. ![image](https://github.com/user-attachments/assets/82ad1970-f2da-49b1-a494-a5abe757693a)

**Desktop (please complete the following information):**
 - OS: windows10
 - 项目属性 
![image](https://github.com/user-attachments/assets/c03d2791-a4f2-406b-ba0c-46f4684cb958)

**Additional context**

**Comment by NotYoojun** [comment]
请看文档。

**Comment by clear-zhao** [comment]
我使用的是
iNKORE.UI.WPF.Modern.Controls.dll [0.9.30.0]
iNKORE.UI.WPF.dll [1.2.8.0]
这个版本是符合要求的吧，隔壁99号帖子的老哥也是这个版本，我起初是以为因为我是net8.0而不是net6.0所以不合适，但是我下载了示例项目， https://github.com/iNKORE-NET/UI.WPF.Modern/blob/main/samples/StarterKit/MainWindow.xaml
我发现你们设置的目标操作系统和我设置的不一样，我是7.0，然后我发现把目标操作系统版本设置为10.0.17763.0以上就不会报这个提示：
NU1701 已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1”而不是项目目标框架“net8.0-windows7.0”还原包“iNKORE.UI.WPF.Modern 0.9.30”。此包可能与项目不完全兼容。
这是这个包只能在固定的目标操作系统版本以上才可以吗，但是我看官方文档说最佳选择是将其设置为 7.0，我有点不懂了
顺便我的操作系统内部版本是19045.5011
