### ISSUE TITLE
[Special] 在未来加入更多独占 FDS 控件

### ISSUE THREAD

**Issue by Aris-Offline** [iNKORE-NET/UI.WPF.Modern#106]
### Discussed in https://github.com/iNKORE-NET/UI.WPF.Modern/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **Aris-Offline** November  9, 2024</sup>
> 对周前一次有关 .NET 9 中的 Fluent 样式的讨论的总结。

由于微软将在 .NET 9 加入内置 WPF Fluent 样式，如果微软发挥超常，那么包括 UI.WPF.Modern 和 WPF UI 在内的一众以 FDS 为特点的第三方 UI 库就面临着被取代的风险。

由于我们已经由桌面开发转向 Web 开发为主，因此在 iUWM 的精力将大大缩减，停更这个项目也在我们的考虑之内。

然而我们想尽可能保持 iUWM 的发展和维护，因此我们提出了一个想法：在坚持 FDS 的同时逐步制作独占的控件及（可能的）风格。

这个想法仍不成熟，欢迎各位提出意见！</div>

<div type='discussions-op-text'>

> A summary of the previous week's discussion about Fluent styles in .NET 9.

With Microsoft adding built-in WPF Fluent styles to .NET 9, a number of third-party UI libraries featuring FDS, including UI.WPF.Modern and WPF UI, are at risk of being superseded if Microsoft overplays its hand.

As we have shifted from desktop to web-based development, our focus on iUWM will be greatly reduced, and we are considering discontinuing the project.However, we want to keep iUWM developed and maintained as much as possible, so we've come up with the idea of gradually creating exclusive controls and (possibly) styles while sticking to FDS.

This idea is still immature and we welcome your comments! </div>

**Comment by Aris-Offline** [comment]
可以前往 #104 进行讨论

**Comment by NotYoojun** [comment]
在具体计划和细节决定之前请使用 discussion，而不是 issue。
