### ISSUE TITLE
[Bug] Windows10下Acrylic窗口材质的问题

### ISSUE THREAD

**Issue by ROCmirs** [iNKORE-NET/UI.WPF.Modern#107]
**描述**
在Windows10中，使用Acrylic材质创建的窗口可以正常显示加载；但是在拖动窗口时会发生异常卡顿，需要非常长事件才能到达指定位置；窗口内部其他控件正常显示与交互无异常延迟。

**复现**
复现方法：在windows10环境下打开窗口，拖动标题栏使其改变位置
概率：几乎每次

**期望效果**
正常移动窗口无延迟

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/c7fb3f4d-6000-420f-b4b1-53e7540680a8)
https://github.com/user-attachments/assets/4d12752a-fbd5-4696-817d-c8089c493ebc

**系统与版本**
 - 系统: Windows 10 22H2 x64 (VM Workstation 17虚拟机平台)
 - 版本: iNKORE-NET / UI.WPF.Modern 0.9.28.0 NuGet: 0.9.30

**Comment by NotYoojun** [comment]
是这样，微软 api 的问题，暂时还没找到解决办法。

**Comment by NotYoojun** [comment]
由于我手上没有 win10 的电脑不太好开发，看各位有没有好办法 🙏🏻🙏🏻

**Comment by melinyi** [comment]
> 由于我手上没有 win10 的电脑不太好开发，只能看各位有没有好办法了 🙏🏻🙏🏻

可以在移动窗口时关闭API，松开时再复原。实现移动时关闭，结束开启闭合。

**Comment by NotYoojun** [comment]
这个就是自己的事了，如果由一个通用的库来实现的话实在没必要
