### ISSUE TITLE
Solution files

### ISSUE THREAD

**Issue by JeremyAnsel** [iNKORE-NET/UI.WPF.Modern#109]
In the repository there are 2 sln files:
- /iNKORE.UI.WPF.Modern.sln
- /source/iNKORE.UI.WPF.Modern.sln

Which one is valid?

**Comment by NotYoojun** [comment]
Use `/iNKORE.UI.WPF.Modern.sln`
Fixed in https://github.com/iNKORE-NET/UI.WPF.Modern/commit/4a8a04f945174133265276f56efe09cd3f605ea9
