### ISSUE TITLE
Navigate在执行页面切换时，一些控件不会产生切换过渡动画

### ISSUE THREAD

**Issue by 541728305** [iNKORE-NET/UI.WPF.Modern#112]
https://github.com/user-attachments/assets/4179706d-e99c-494a-81d0-e8442ce53ef1
![image](https://github.com/user-attachments/assets/e47c27bf-53be-47fb-8023-e3e55fe1850e)

页面切换的时候，第三方控件（HWindowControl）不会产生过渡动画效果

**Comment by NotYoojun** [comment]
这是 winform 等 win32 组件吗

**Comment by NotYoojun** [comment]
如果是 win32 组件的话，是做不到动画的，同时你也会发现这个控件无论如何也不会被其他 wpf 控件遮挡，这是一个典型的空域问题：

> 在使用WPF开发监控软件时，通常要使用相机软件自带的官方SDK,但是大多数SDK通过控件句柄进行图像显示，比较常见的包括海康威视以及微视的多款相机。但是WPF控件都是使用像素进行绘制，不存在控件句柄，即使获得的句柄也只是整个窗体的句柄。鉴于微软官方提供的WindowsFormHost能够将Winform控件引入WPF中，故通过此方式我们能够实现在WPF中使用winfrom控件的句柄。但是由于WPF使用DiretcX进行渲染，而Winfrom使用GDI进行渲染，由于GDI的渲染慢于DirectX，故显示出的软件界面，Winfrom控件始终处于最上层。

> WPF的原生控件并不具备自身的句柄，即使使用偏门的方式获取的结果也都是控件所在窗体的句柄，并不代表该控件本身的资源，这是由WPF的自身的机制决定的。
> ```csharp
> IntPtr hwnd1 = new WindowInteropHelper(this).Handle; 
> IntPtr hwnd2 = ((HwndSource)PresentationSource.FromVisual(uielement)).Handle;
> ```
> 
> 到此需要了解下Winform与WPF的区别，WPF和winform最大的区别在于WPF底层使用的DirectX，winform底层使用的是GDI+,所以WPF的图形界面上更胜一筹。
> GDI+(Graphics Device Interface)图形设备接口，它的主要任务是负责绘图程序之间的信息交换、处理，所有windows程序的图形输出
> DirectX(Direct Extension)多媒体编程接口，加强3D图形和声音效果，有很多API组成。按照性质分类可分为四大部分：显示部分，声音部分，输入部分和网络部分。

https://blog.csdn.net/aniston_luo/article/details/115863091
https://cloud.tencent.com/developer/article/1760999

**Comment by 541728305** [comment]
有没有过渡动画的Completed事件，我打算动画结束之前先隐藏它

**Comment by NotYoojun** [comment]
暂时没有，如果需求比较多的话可以加，或者你可以提 pr

**Comment by 541728305** [comment]
好的，感谢

**Comment by 541728305** [comment]
> 暂时没有，如果需求比较多的话可以加，或者你可以提 pr

好的，感谢
