### ISSUE TITLE
User control issue in the app

### ISSUE THREAD

**Issue by sumit-codebrewer** [iNKORE-NET/UI.WPF.Modern#47]
The library looks good on my application, it has several styles that are making my windows look modern. Like, this how I implemented a settings page in my app.

<img width="593" alt="image" src="https://github.com/iNKORE-Public/UI.WPF.Modern/assets/71552669/4e1a225a-c5af-4929-b628-329815304576">

The issue is, when I am trying to enable the same modern styles on the user control, it is showing different behaviour. Like this is how the buttons are looking here.
<img width="257" alt="image" src="https://github.com/iNKORE-Public/UI.WPF.Modern/assets/71552669/d3317190-06d2-492c-bb78-8d65e9e6d584">

<img width="452" alt="image" src="https://github.com/iNKORE-Public/UI.WPF.Modern/assets/71552669/c4ccd123-413b-49a9-9fe4-8425129a1375">

Kindly suggest a way to fix the same, so that the user control have the same properties as a normal window.

**Comment by sumit-codebrewer** [comment]
This is how the code looks like:
  <UserControl>
                    <DataTemplate>
                        <Button
                            Height="30"
                            Padding="8,0,8,0"
                            Command="{Binding ButtonClickCommand}"
                            Content="{Binding ButtonContent}">
                        </Button>
                    </DataTemplate>

</UserControl>

**Comment by NotYoojun** [comment]
Where did you put `ThemeResource` and `XamlControlResource` in?
They should be put in the App.Resources. Did you follow the [Quick Start Guide](https://github.com/iNKORE-Public/UI.WPF.Modern/blob/main/docs/Quick%20Start.md)?

**Comment by sumit-codebrewer** [comment]
I put that in app.xaml and it is applying the modern styles in every window. But talking about User control, it is not showing the same behaviour in this case.

Ideally, I want this kind of color in dark theme
<img width="262" alt="image" src="https://github.com/iNKORE-Public/UI.WPF.Modern/assets/71552669/93c5d956-7a39-42ef-a987-6dd1131ebd2c">

What I am getting in case of user control being called in another window
<img width="197" alt="image" src="https://github.com/iNKORE-Public/UI.WPF.Modern/assets/71552669/d0ce999c-f134-43d9-bf1d-0d9eed270315">


Any ideas, how to fix this?

**Comment by biocross** [comment]
I was able to get this to work for UserControl by manually merging resources for UserControl, and then forcing the style on the buttons:

```
<UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>
```

```
<Button
Content="{Binding ButtonContent}"
Style="{StaticResource DefaultButtonStyle}">
```

**Comment by NotYoojun** [comment]
> I was able to get this to work for UserControl by manually merging resources for UserControl, and then forcing the style on the buttons:
> 
> ```
> <UserControl.Resources>
>         <ResourceDictionary>
>             <ResourceDictionary.MergedDictionaries>
>                 <ui:ThemeResources />
>                 <ui:XamlControlsResources />
>             </ResourceDictionary.MergedDictionaries>
>         </ResourceDictionary>
>     </UserControl.Resources>
> ```
> 
> ```
> <Button
> Content="{Binding ButtonContent}"
> Style="{StaticResource DefaultButtonStyle}">
> ```

I don't think this is a good idea. It will make the theme resources loaded twice.
What about adding those to DesignTimeResources?

**Comment by biocross** [comment]
Any guides on how I can do this? Would really appreciate it - sorry I'm a little new to WPF development

**Comment by biocross** [comment]
OK removing the `UserControl.Resources` and just manually specifying the style in the Button fixed the issue for me:

```
<Button
Content="{Binding ButtonContent}"
Style="{StaticResource DefaultButtonStyle}">
```

**Comment by NotYoojun** [comment]
@biocross Maybe this solution is not bad.

However, in my scenario, everything works fine when adding themes into app.xaml.

I don't know why this doesn't work for you guys. I'm really confused.

**Comment by NotYoojun** [comment]
I'm closing this due to long inactivity, feel free to reopen if the issue still exists.
