### ISSUE TITLE
Combobox bug

### ISSUE THREAD

**Issue by Bober95** [iNKORE-NET/UI.WPF.Modern#52]
In the case of a large list of elements, if it is not selected in 1 position, it will always move to the bottom. If there are few items, it will be done in step 1. The video shows when the number of elements is much larger

https://www.youtube.com/shorts/4FB7YnwX6As

 - OS: Windows 11 23H2
 - .Net 8

**Comment by NotYoojun** [comment]
Hi there

This bug has been existing for a long time.
Unfortunately, I haven't found a way to fix it yet. 🥴

**Comment by Bober95** [comment]
The problem is the use of the value - ForceUseSmoothScroll in ScrollViewerEx. After turning it off, this effect no longer occurs.

How to get to this value from Combobox in wpf?

Once I determine why exactly this is happening, I will let you know

**Comment by Valkirie** [comment]
> The problem is the use of the value - ForceUseSmoothScroll in ScrollViewerEx. After turning it off, this effect no longer occurs.
> 
> How to get to this value from Combobox in wpf?
> 
> Once I determine why exactly this is happening, I will let you know

Interested in hearing from you here once "fixed". Ideally we'd be able to only change the ComboBox own scrollviewer.

**Comment by NotYoojun** [comment]
Hi there, I'll dig into this when I get home. Thanks for ur ideas!

**Comment by NotYoojun** [comment]
Please try the latest commit, I applied your idea there. Could you please build the latest version and check if it still exists.

**Comment by Bober95** [comment]
Hello, this problem has been fixed, but there is still one error - when we change using the arrow keys on the keyboard, the list does not follow the currently selected item.
I tried to find a solution to this myself, unfortunately to no avail at the moment.

**Comment by CasperH2O** [comment]
@NotYoojun @Bober95 if I may, is this similar to the problem we are having? It looks like this when using "Tab" to navigate through the elements in the drop down.

[329247983-4b7bd0a6-391e-4e14-a000-6154f197a41a.webm](https://github.com/iNKORE-NET/UI.WPF.Modern/assets/14330834/e5199f4a-35e5-4da6-9b33-07398a644246)

More details here: https://github.com/Valkirie/HandheldCompanion/issues/1048

**Comment by Bober95** [comment]
> if I may, is this similar to the problem we are having?
Yes, that's it. The drop-down list does not track the selected item

**Comment by NotYoojun** [comment]
Hey, does this exist before my changes?

Btw I'm afraid I need to close this issue as completed since the first question is fixed.

Could you please open a new issue for this problem? Thks

**Comment by Bober95** [comment]
> Hey, does this exist before my changes?

Yes
