### ISSUE TITLE
How to disable close buttons on tabs

### ISSUE THREAD

**Issue by ekdahl** [iNKORE-NET/UI.WPF.Modern#56]
Since switching to this library, there are close buttons on all tabs. I can't figure out how to disable or hide the close buttons on TabItems by default. What property should I change to do that?

**Comment by NotYoojun** [comment]
Hi there,

You can set **ui:TabControlHelper.IsAddTabButtonVisible** to false, or apply the Pivot style for yout TabControl.

For more information, please see our docs [here](https://github.com/iNKORE-NET/Documentation/blob/main/data/docs/ui.wpf.modern/03.%20components/08.%20navigation/%23%20tab-control/index.en-US.mdx).

> # About our docs
> We're currently working on a documentation site that simplifies your learning curve. However this can be a huge process.
>
> Before everything is done, you can view our unfinished works [here](https://github.com/iNKORE-NET/Documentation). PRs are also welcomed.
>
> When we finish everything, the docs will be available on `docs.inkore.net`

**Comment by ekdahl** [comment]
Thanks, that worked!

**Comment by NotYoojun** [comment]
Happy to hear that. Feel free to ask if you have any questions 😀

**Comment by NotYoojun** [comment]
Hi,

Please check: https://docs.inkore.net/ui-wpf-modern/components/navigation/tab-control
