### ISSUE TITLE
CLIPBRD_E_CANT_OPEN

### ISSUE THREAD

**Issue by Bober95** [iNKORE-NET/UI.WPF.Modern#58]
Copying text from MessageBox sometimes causes the application to crash with error: 0x800401D0 (CLIPBRD_E_CANT_OPEN)

The solution to this is to use "Clipboard.SetDataObject" instead of "Clipboard.SetText"

**Comment by NotYoojun** [comment]
Hi there,
Please try the latest version (0.9.28) and check if this problem still exists.

**Comment by Bober95** [comment]
We can conclude that the error does not currently occur. However, if it happens again, I will contact you
