### ISSUE TITLE
Maximize snap layout on second screen

### ISSUE THREAD

**Issue by Bober95** [iNKORE-NET/UI.WPF.Modern#60]
**Describe the bug**
The button and snaplayout do not work when the window is on the second screen
![150358641-d646bfa5-fa66-4264-bfb4-4259029bd6bb](https://github.com/iNKORE-NET/UI.WPF.Modern/assets/17840111/c2e23715-8edb-4d9c-ad06-48ab46a3adca)

- OS: Windows 11 23H2
- .Net 8

**Comment by NotYoojun** [comment]
Hello

Thanks for ur feedback. However, I'm sorry that I don't have a second display to test with.

If you got a way to fix it, please don't hesitate to open a PR or contact me.

**Comment by Bober95** [comment]
ok, I found the solution :)

https://stackoverflow.com/questions/49288552/how-do-i-read-the-win32-wm-move-lparam-x-y-coordinates-in-c

File: Helpers/Styles/SnapLayout
Function: IsOverButton

Change: 
`int positionX = lParam.ToInt32() & 0xffff;
 int positionY = lParam.ToInt32() >> 16;`

To:
`uint lparam32 = (uint)lParam.ToInt64();
short positionX = (short)(lparam32 & 0xffff);
short positionY = (short)((lparam32 >> 16) & 0xffff);`

**Comment by NotYoojun** [comment]
Hi there, I'll dig into this when I get home. Thanks for ur ideas!

**Comment by NotYoojun** [comment]
Please try the latest commit, I applied your idea there. Could you please build the latest version and check if it still exists.

**Comment by Bober95** [comment]
Thanks, it works!

**Comment by NotYoojun** [comment]
Hi there, could you guys please drop us a five star for the gallery app on Microsoft Store?
Your feedback really helps us a lot! Pretty please? Thanks so much!
@Bober95 @Valkirie @ghost1372 @JeremyAnsel 

https://www.microsoft.com/store/productId/9N3JS11ZC38G

**Comment by ghost1372** [comment]
Hi @NotYoojun 
Done.🌟🌟🌟🌟🌟
also if you have any time 😁🙏
https://apps.microsoft.com/search/publisher?name=Mahdi+Hosseini&hl=en-us&gl=US

**Comment by ghost1372** [comment]
also, did you try WPF .Net 9 Preview Gallery App? it is Worse🤣

**Comment by NotYoojun** [comment]
> also, did you try WPF .Net 9 Preview Gallery App? it is Worse🤣

Yeah I've downloaded it and I have to say it just sucks.
No details, no animations, there's nothing at all...

**Comment by NotYoojun** [comment]
> Hi @NotYoojun Done.🌟🌟🌟🌟🌟 also if you have any time 😁🙏 https://apps.microsoft.com/search/publisher?name=Mahdi+Hosseini&hl=en-us&gl=US

Love it, and five stars has been dropped!

**Comment by ghost1372** [comment]
> > Hi @NotYoojun Done.🌟🌟🌟🌟🌟 also if you have any time 😁🙏 https://apps.microsoft.com/search/publisher?name=Mahdi+Hosseini&hl=en-us&gl=US
> 
> Love it, and five stars has been dropped!
> The only pity is that the package is too large.
> Did you packed the whole .NET runtime?
> It took me really a long time to download.

Yes, Self Contained for Net and WASDK, every architecture (x64, x86, arm) size is almost 80mb. I can reduce it by removing self contained but i think user may face with some issues

**Comment by NotYoojun** [comment]
That just takes away a lot of trouble, ain't it?
Even though I'm again Self-contained, I have to admit that it's really convenient sometimes.
😂😂
