### ISSUE TITLE
调整主题色问题

### ISSUE THREAD

**Issue by gcc2001** [iNKORE-NET/UI.WPF.Modern#65]
我想自定义程序的主题色，但是看到gallery中没有展示调整主题色的代码，不知道是默认没有提供api，还是需要自己实现呢？

**Comment by NotYoojun** [comment]
有办法改，等我把这篇文档写好了告诉你

**Comment by NotYoojun** [comment]
你好，

这篇文档已经写好了，请参见：
https://docs.inkore.net/ui-wpf-modern/features/theming/accent-color

(目前还没时间写中文版，如有需要可以用 Google Translator)

**Comment by NotYoojun** [comment]
> 谢谢，可以调整主题色了。
> 
> 想再问一下，是否有计划提供colorpicker的组件呢？

iNKORE.UI.WPF 里面有 ColorPicker。
https://github.com/iNKORE-NET/UI.WPF

WinUI 的 ColorPicker 太难用，就不准备搬过来了。
