### ISSUE TITLE
Feat Suggest: 支持文字类型的InfoBadge

### ISSUE THREAD

**Issue by LxHTT** [iNKORE-NET/UI.WPF.Modern#68]
效果可参考：
![image](https://github.com/iNKORE-NET/UI.WPF.Modern/assets/98154001/ac41e2bc-2c6b-4a03-984d-fb0320bff505)

**Comment by NotYoojun** [comment]
c# 搞不了联合类型，有点麻烦

**Comment by NotYoojun** [comment]
再有 infobadge 也不是这么玩的。我想如果你实在要这样的话还是用 border 吧，又能自定义圆角和尺寸。

**Comment by LxHTT** [comment]
行
