### ISSUE TITLE
建议写一个 winui 类似的 SettingsCard

### ISSUE THREAD

**Issue by duduskz** [iNKORE-NET/UI.WPF.Modern#69]
如图，使用Border确实能实现大概的效果，不过Border主题色啥的每个Page都要声明一次，属实有点麻烦
并且Border实现的动画也比较生硬，比如Expander点开时，用原生的Expander实现的话就直接弹出来了，字多的话有点突然。而winui的SettingsExpander弹开有一段弹出动画

**Comment by NotYoojun** [comment]
你好，后续请关注 #75 的进展。

**Comment by NotYoojun** [comment]
# 🎉 This issue has been fixed in iNKORE.UI.WPF.Modern 0.10.0!
More features and bug fixes available
Check out: https://github.com/iNKORE-NET/UI.WPF.Modern/releases/tag/v0.10.0
