### ISSUE TITLE
Windows 11's icons for title bar caption buttons when UI.WPF.Modern is running on Windows 11

### ISSUE THREAD

**Issue by IviriusMain** [iNKORE-NET/UI.WPF.Modern#70]
![image](https://github.com/iNKORE-NET/UI.WPF.Modern/assets/106150547/ea2e7b05-3c49-4889-8e79-a12ff15aaa7e)
Use these icons for Windows 11

**Comment by NotYoojun** [comment]
Hi, I did something and added `ui:TitleBar.ButtonGlyphStyle` property on this commit:
https://github.com/iNKORE-NET/UI.WPF.Modern/commit/d52041b5d0356c347629f0e0015c2f2caeb7622c

Could you please help me test it?
Thanks

**Comment by NotYoojun** [comment]
This is done!
