### ISSUE TITLE
Extend TabView (TabControl) tabs in title bar

### ISSUE THREAD

**Issue by manfromarce** [iNKORE-NET/UI.WPF.Modern#71]
**Describe the solution you'd like**
This library is awesome. It would be a nice addition if a TabView could be extended in the title bar, as it can be achieved in WinUI 3 / UWP. A sample could also be added to the gallery app.

**Describe alternatives you've considered**
I have tried adding a panel with fixed minimum width and a TitleBar control to the TabStripFooter and setting ExtendViewIntoTitleBar to true, as this is how it's usually done in WinUI, but the tabs and buttons are not hit test visible this way.

**Comment by NotYoojun** [comment]
WindowChrome.IsHitTestVisibleInChrome property needs to be used.

**Comment by NotYoojun** [comment]
I'm closing this due to long inactivity, feel free to reopen if the issue still exists.
