### ISSUE TITLE
TitleBar and window borders not responding to mouse when view is extended to title bar 

### ISSUE THREAD

**Issue by softinitializing** [iNKORE-NET/UI.WPF.Modern#74]
Hi, 
I have Extended View Into TitleBar to but a menu and some other controls like a toggle switch to switch between dark and light themes then i set ` WindowChrome.IsHitTestVisibleInChrome="True"` to get the controls to work 
the main title bar layout is grid divided to columns like this 

`        <Grid IsHitTestVisible="True">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="49" />
                <ColumnDefinition Width="325" />
                <ColumnDefinition Width="*" />
                <ColumnDefinition Width="Auto" MinWidth="100" />
                <ColumnDefinition Width="20" />

                <ColumnDefinition Width="200" />

            </Grid.ColumnDefinitions>
            <Image
                Width="28"
                Height="28"
                Margin="8,0,0,0"
                Source="/Assets/FlverStudio.ico" />
            <Menu
                Grid.Column="1"
                Height="32"
                Margin="0,0,0,0"
                IsHitTestVisible="True">
                <MenuItem
                    Height="32"
                    FontFamily="{StaticResource GlobalFontFamily}"
                    FontSize="18"
                    Header="File"
                    IsHitTestVisible="True">
                    <MenuItem  Header="G" />
                </MenuItem>
                <MenuItem
                    Height="32"
                    FontFamily="{StaticResource GlobalFontFamily}"
                    FontSize="18"
                    Header="Armature">
                    <MenuItem Header="G" />
                </MenuItem>
                <MenuItem
                    Height="32"
                    FontFamily="{StaticResource GlobalFontFamily}"
                    FontSize="18"
                    Header="Meshes">
                    <MenuItem Header="G" />
                </MenuItem>
                <MenuItem
                    Height="32"
                    FontFamily="{StaticResource GlobalFontFamily}"
                    FontSize="18"
                    Header="Dummies">
                    <MenuItem Header="G" />
                </MenuItem>
                <MenuItem
                    Height="32"
                    FontFamily="{StaticResource GlobalFontFamily}"
                    FontSize="18"
                    Header="Materials">
                    <MenuItem Header="G" />
                </MenuItem>

            </Menu>
            <TextBlock
                Grid.Column="3"
                Width="Auto"
                Background="#997B7B7B"
                IsHitTestVisible="False"
                Text="" />
            <ui:ToggleSwitch
                x:Name="ThemeToggler"
                Grid.Column="5"
                Margin="0,0,20,0"
                HorizontalAlignment="Stretch"
                OffContent=""
                OnContent=""
                Toggled="ThemeToggler_Toggled"
                UseSystemFocusVisuals="True" />
            <Rectangle
                Grid.Column="2"
                Fill="Transparent"
                IsHitTestVisible="False" />
        </Grid>
`
the rectangle hit test is false to pass mouse input to title bar 
so far things work as expected where the title bar will drag the window when the rectangle is dragged  , but when setting
 ` ui:WindowHelper.SystemBackdropType="None"` the title bar no longer responds like before .

**Comment by NotYoojun** [comment]
Hi,

Please check #71.
You should use `WindowChrome.IsHitTestVisibleInChrome` property.

**Comment by softinitializing** [comment]
> Hi,
> 
> Please check #71. You should use `WindowChrome.IsHitTestVisibleInChrome` property.

thanks for replaying 
yes i am aware of this property and already implement it it in my window 
and it works when` SystemBackdropType="Meca"` or something else 
the problem is when `SystemBackdropType="None"` here the title bar stops working as before



`Window
    x:Class="Studio.Views.StudioWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:controls="clr-namespace:FlverStudioExtras.Controls;assembly=FlverStudioExtras"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:docking="http://schemas.xceed.com/wpf/xaml/avalondock"
    xmlns:excomponents="clr-namespace:StudioExtras.Components;assembly=StudioExtras"
    xmlns:local="clr-namespace:Studio.Views"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:svgc="http://sharpvectors.codeplex.com/svgc/"
    xmlns:syncfusion="http://schemas.syncfusion.com/wpf"
    xmlns:syncfusionskin="clr-namespace:Syncfusion.SfSkinManager;assembly=Syncfusion.SfSkinManager.WPF"
    xmlns:sys="clr-namespace:System;assembly=System.Runtime"
    xmlns:ui="http://schemas.inkore.net/lib/ui/wpf/modern"
    xmlns:viewmodels="clr-namespace:Studio.ViewModels"
    Title=""
    Width="1080"
    Height="720"
    d:Background="DimGray"
    d:DataContext="{d:DesignInstance Type=viewmodels:StudioViewModel}"
    ui:ThemeManager.IsThemeAware="True"
    ui:TitleBar.ExtendViewIntoTitleBar="True"
    ui:TitleBar.Height="32"
    ui:WindowHelper.SystemBackdropType="None"
    ui:WindowHelper.UseModernWindowStyle="True"
    WindowChrome.IsHitTestVisibleInChrome="True"
    WindowState="Maximized"
    mc:Ignorable="d">`

**Comment by NotYoojun** [comment]
That's not correct, you're supposed to add IsHitTestVisibleInChrome into the control in the title bar which you want to be interactive, not the whole window. 🙄😓🤦🏻

**Comment by softinitializing** [comment]
That's makes sense 🙇‍♂️
