### ISSUE TITLE
[Bug] Windows 7未启用Aero时，程序颜色管理乱套

### ISSUE THREAD

**Issue by LxHTT** [iNKORE-NET/UI.WPF.Modern#76]
**Describe the bug**
Windows 7未启用Aero时，浅色模式的App背景为黑，控件为浅色导致显示不正确。  
深色模式/跟随系统正常。

**To Reproduce**
在浅色模式下打开App

**Expected behavior**
整个都是浅色模式

**Screenshots**
![Snipaste_2024-08-09_15-56-52](https://github.com/user-attachments/assets/98e99b53-6110-42c3-b084-da215c9b744f)

**Desktop (please complete the following information):**
 - OS: Windows 7 Service Pack 1

**Comment by NotYoojun** [comment]
请尝试编译仓库中还未发布的最新源码，我记得应该修了

![image](https://github.com/user-attachments/assets/2d5846aa-2c66-4a84-94e8-bc3eeb9cf9ca)

**Comment by LxHTT** [comment]
fixed

**Comment by NotYoojun** [comment]
Fixed right now, nuget will be available in the next version.

**Comment by NotYoojun** [comment]
# 🎉 This issue has been fixed in iNKORE.UI.WPF.Modern 0.10.0!
More features and bug fixes available
Check out: https://github.com/iNKORE-NET/UI.WPF.Modern/releases/tag/v0.10.0
