### ISSUE TITLE
冒昧问一下官方Gallary在哪下载

### ISSUE THREAD

**Issue by s1one2009** [iNKORE-NET/UI.WPF.Modern#79]
如题
README.md那个Gallary的截图很美
找半天找不到Gallary在哪下载
冒昧问一下官方Gallary在哪下载
要是没开放下载可以开放下载吗
谢

**Comment by s1one2009** [comment]
在Microsoft Store找到了

**Comment by NotYoojun** [comment]
如果想要最新版可以自己 clone 然后编译，源码都在仓库里+

**Comment by s1one2009** [comment]
谢谢
已经找到了
