### ISSUE TITLE
ScrollViewerEx can not auto scroll

### ISSUE THREAD

**Issue by wuyang26** [iNKORE-NET/UI.WPF.Modern#81]
When using ScrollViewerEx on a Listbox, if an item is partially obscured, 
clicking on it with the mouse will automatically scroll to full display if using ScrollViewer, while ScrollViewerEx will have no response.
![image](https://github.com/user-attachments/assets/1bbabb01-ef1d-4d27-9dd5-b3d03476ce8f)

**Comment by wuyang26** [comment]
At the same time If ScrollViewerEx is used with the ComboBox control, it will not automatically scroll to the selection when clicking the drop-down button.

**Comment by Bober95** [comment]
https://github.com/iNKORE-NET/UI.WPF.Modern/blob/8620356967c85ddaa8da42422e0c940e43e03bce/source/iNKORE.UI.WPF.Modern/Controls/ScrollViewerEx.cs#L108

If you remove the ScrollInfo override everything starts working normally

**Comment by wuyang26** [comment]
After deleting this code, an error occurred while running for ListBox Control.

**Comment by NotYoojun** [comment]
Hey,

Pls check after the latest commit if the problem still exists.

**Comment by NotYoojun** [comment]
> After deleting this code, an error occurred while running for ListBox Control.

Does this problem appear in the latest code?

**Comment by NotYoojun** [comment]
I'm closing this due to long inactivity, feel free to reopen if the issue still exists.
