### ISSUE TITLE
The BorderThickness="0" is not have any effect when applied to RichTextBox

### ISSUE THREAD

**Issue by GID0317** [iNKORE-NET/UI.WPF.Modern#82]
**Describe the bug**
I encountered an issue with the RichTextBox control in the library. When setting the BorderThickness property to 0, the border is still visible, and the focus underline appears. This behavior is inconsistent with the TextBox control, where setting BorderThickness to 0 successfully hides the border and focus underline.

**To Reproduce**
1. Create a RichTextBox control.
2. Set the BorderThickness property to 0.
3. Set the BorderBrush property to Transparent.
4. Run the application and observe the RichTextBox when it gains focus.

**Expected behavior**
RichTextBox should not display any border or focus underline when BorderThickness is set to 0 and BorderBrush is set to Transparent.

**Screenshots**
![Screenshot 2024-08-16 192209](https://github.com/user-attachments/assets/c832ef4a-3505-44ef-aabd-142821228d44)

**Additional context**
The RichTextBox still displays a border and focus underline despite setting BorderThickness to 0 and BorderBrush to Transparent.
<RichTextBox Background="Transparent" BorderThickness="0" BorderBrush="Transparent" Opacity="1" Margin="10" Padding="10" VerticalAlignment="Bottom" HorizontalAlignment="Left" Width="300" Height="200" IsReadOnly="True" VerticalScrollBarVisibility="Hidden" FontSize="12" CaretBrush="Transparent" />

**Comment by NotYoojun** [comment]
Hi, according to WinUI guidelines, when the box is foucsed, the BorderThickness will be set to a different value called `TextControlBorderThemeThicknessFocused`. If you want to remove the focused border, you can do as follows:

```xml
<RichTextBox BorderThickness="0">
    <FrameworkElement.Resources>
        <Thickness x:Key="{x:Static ui:ThemeKeys.TextControlBorderThemeThicknessFocusedKey}"></Thickness>
    </FrameworkElement.Resources>
</RichTextBox>
```

This will be mentioned in the future documentation.

**Comment by GID0317** [comment]
Thanks!  can’t wait to see it in the documentation. I’ll close this issue as completed.

**Comment by GID0317** [comment]
Thank you! I'll check it out
