### ISSUE TITLE
[Bug] Broke title bar when "Show accent color on window broders" is on

### ISSUE THREAD

**Issue by NotYoojun** [iNKORE-NET/UI.WPF.Modern#84]
Window chrome issue?
Image
Clicking on the arrow on nav view shouldn't select the item
Image
NσȶƳơơʝʊռ (˶⍤⃝˶꒳ᵒ꒳ᵎ ).! — Today at 9:06 AM
Hahaha camman is finally happy now
NσȶƳơơʝʊռ (˶⍤⃝˶꒳ᵒ꒳ᵎ ).! — Today at 9:06 AM
This is weird
I haven't received any similar reports
Ivirius — Today at 9:08 AM
Well apparently accent color on window title bars is broken
And that might be because nobody uses accent color
NσȶƳơơʝʊռ (˶⍤⃝˶꒳ᵒ꒳ᵎ ).! — Today at 9:09 AM
Lemme check it later on my PC
Image
Dang
When this is on the issue appears
Image

![image](https://github.com/user-attachments/assets/fc313655-adc7-40d3-a023-7ede4318e4d0)

![image](https://github.com/user-attachments/assets/c6b33ea5-dbcb-4288-a8ca-69ab35599d12)

**Comment by Bober95** [comment]
The solution is commented in the code :)

[var captionColor = -2; //DWMWA_COLOR_NONE - 0xFFFFFFFE
			DWMAPI.DwmSetWindowAttribute(handle, DWMAPI.DWMWINDOWATTRIBUTE.DWMWA_CAPTION_COLOR,
				ref captionColor,
				Marshal.SizeOf(typeof(int)));](https://github.com/iNKORE-NET/UI.WPF.Modern/blob/8620356967c85ddaa8da42422e0c940e43e03bce/source/iNKORE.UI.WPF.Modern/Helpers/Styles/BackdropHelper.cs#L83)

**Comment by NotYoojun** [comment]
Hi, please try the latest code.
If anything's wrong, feel free to reopen this.
