### ISSUE TITLE
[Bug] RatingControl doesn’t follow the accent color the dark/light mode color contrast.

### ISSUE THREAD

**Issue by GID0317** [iNKORE-NET/UI.WPF.Modern#85]
Now: 
dark mode (HEX #0078d4)
![image](https://github.com/user-attachments/assets/d5a3dabe-6198-404e-a5bf-84fcb079f795)
Light mode (HEX #0078d4)
![image](https://github.com/user-attachments/assets/d3dfc954-13bc-4f08-a51a-3efc96774139)

What it should look like:
dark mode (HEX #4cc2ff)
![image](https://github.com/user-attachments/assets/1a7aba57-dfe7-4ee1-975a-9ee969bf683e)
Light mode (HEX #0067c0)
![image](https://github.com/user-attachments/assets/59d6229e-440d-4bf1-bfaf-4197d2113b72)

**Comment by NotYoojun** [comment]
Hi, please check the latest code. It is supposed to be fixed now.
If anything's wrong, feel free to reopen this issue!

**Comment by GID0317** [comment]
Hi, after reviewing the latest build, it seems the contrast issue has been resolved. However, there is a problem with the unselected rating controls; the non-selected stars do not appear as they do in WinUI.
Current:
![WPF_Stars](https://github.com/user-attachments/assets/c31690a1-39db-4b10-98f7-3235f6d6279a)
Winui:
![WINUI_Stars](https://github.com/user-attachments/assets/06bc06e5-4ee5-42a5-93b6-e0e04abc81cb)

I believe it was off-topic, but I will list the others as well to prevent flooding the issue list.
SelectionHighlightColor has a wrong color contrast
Current:
![Screenshot 2024-09-01 191429](https://github.com/user-attachments/assets/69fc0487-5e4d-4391-b63b-2304d3b61532)
![image](https://github.com/user-attachments/assets/c795443f-5a9e-4039-acb2-b2c773ff0632)
WinUI:
![image](https://github.com/user-attachments/assets/afacfaaa-91f4-4731-b2ea-988999ee8254)
![image](https://github.com/user-attachments/assets/0f0172f1-79b7-4e00-a1bf-5e72b33945e2)
DropDownButton with Icons (The icon is using old symbol on the current)
Current:
![Screenshot 2024-09-01 153349](https://github.com/user-attachments/assets/5afb6465-6d7d-43ee-b2ad-1e26c5ead910)
WinUI:
![Screenshot 2024-09-01 153340](https://github.com/user-attachments/assets/42b88e63-218a-4013-b288-1ad3856b12c2)

Split Button border was colored black instead white on dark mode
Current:
![WPF](https://github.com/user-attachments/assets/5d514e8c-8036-4944-b049-56c48f11ffab)
![WPF_Splitutton](https://github.com/user-attachments/assets/3607f902-7323-4e06-98d6-c0464e593efb)
![WPF_Splitutton (2)](https://github.com/user-attachments/assets/501ba0a5-8938-4ec0-9d24-d46a21dc7adb)
WinUI:
![WINUI](https://github.com/user-attachments/assets/4f76e72e-5ce4-434b-91a4-dc250abc7781)
![WINUI_Splitutton](https://github.com/user-attachments/assets/cd8f842e-571b-4f3f-8117-522932503714)
![WINUI_Splitutton (2)](https://github.com/user-attachments/assets/c471ba8c-f173-418e-a10c-644f6ac663e6)

FlipView not following the dark theme:
Current:
![WPF_Flipview](https://github.com/user-attachments/assets/183f5973-4d60-4831-82b5-5d8f60fdb1bd)
WInUI:
![Winui_Flipview](https://github.com/user-attachments/assets/7e3c7b2c-2443-4e2b-90e5-cdcd9f09f095)

**Comment by NotYoojun** [comment]
I guess it's better for you to create an issue for each problem you've mentioned.

**Comment by GID0317** [comment]
Thanks, I will create separate issues for each problem as you've recommended.
