### ISSUE TITLE
[Bug] ProgressRing 0 value shown as 1

### ISSUE THREAD

**Issue by MariosKonDev** [iNKORE-NET/UI.WPF.Modern#86]
ProgressRing 0 value shown as 1.

![image](https://github.com/user-attachments/assets/539ad3e7-3ba5-4a62-a3db-fc5129a4cbd2)

**Comment by NotYoojun** [comment]
Hi, please check the latest code. It is supposed to be fixed now.
If anything's wrong, feel free to reopen this issue!

**Comment by MariosKonDev** [comment]
Thank you, Can you please also update it in the nuget package?

**Comment by NotYoojun** [comment]
This will be available in the coming-soon 0.10.0 package. Thanks for ur patience

**Comment by NotYoojun** [comment]
# 🎉 This issue has been fixed in iNKORE.UI.WPF.Modern 0.10.0!
More features and bug fixes available
Check out: https://github.com/iNKORE-NET/UI.WPF.Modern/releases/tag/v0.10.0
