### ISSUE TITLE
Can RadioButtons be arranged at intervals?

### ISSUE THREAD

**Issue by wuyang26** [iNKORE-NET/UI.WPF.Modern#90]
Can RadioButtons be arranged at intervals?

The current method is similar to Grid, but it is not good when the length of the items is different.

**Comment by NotYoojun** [comment]
Sorry, i didn't understand

**Comment by wuyang26** [comment]
The current arrangement is similar to this:
![image](https://github.com/user-attachments/assets/74cd644e-cbd2-402f-9557-fdd019b78e2e)

But I would prefer this way:
![image](https://github.com/user-attachments/assets/a4952069-5e4d-4b59-843f-e8ce6b0f085b)

That is to say, we hope the arrangement method is mainly based on item intervals, rather than fixed widths of item

**Comment by NotYoojun** [comment]
Try setting the MinWidth property to 0 on the radio buttons

**Comment by wuyang26** [comment]
After setting the MinWidth property to 0,the problem still exists.
You can test the app example by setting radio button content of different lengths size ,like the abrove.

**Comment by NotYoojun** [comment]
Check this code:

```xml
<ikw:SimpleStackPanel HorizontalAlignment="Center" VerticalAlignment="Center"
    Spacing="15" Orientation="Horizontal">

    <FrameworkElement.Resources>
        <Style TargetType="RadioButton" BasedOn="{StaticResource {x:Static ui:ThemeKeys.DefaultRadioButtonStyleKey}}">
            <Setter Property="MinWidth" Value="0"/>
            <Setter Property="Background" Value="AliceBlue"/>
        </Style>
    </FrameworkElement.Resources>

    <RadioButton Content="Radio"/>
    <RadioButton Content="Radio Button"/>
    <RadioButton Content="Station"/>
    <RadioButton Content="Button Radio"/>

</ikw:SimpleStackPanel>
```

![image](https://github.com/user-attachments/assets/cc0f6b11-9660-4875-b495-70815d2ef38e)

**Comment by wuyang26** [comment]
Just using RadioButton is definitely not a problem.however, there are issues with using the RadioButtons control

<ui:RadioButtons  HorizontalAlignment="Left" VerticalAlignment="Top" 
     SelectedIndex="{Binding Group2SelectedIndex}" MaxColumns="15">
    <RadioButton  Content="Option 1 length"/>
    <RadioButton  Content="Option 2"/>
    <RadioButton  Content="Option 3 length"/>
    <RadioButton  Content="Option 4"/>
    <RadioButton  Content="Option 5"/>
</ui:RadioButtons>

**Comment by NotYoojun** [comment]
No, you can't do that. Please see the source code of ui:RadioButtons (https://github.com/iNKORE-NET/UI.WPF.Modern/blob/main/source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/RadioButtons/RadioButtons.xaml).

Inside the component a UniformGrid-based panel is used for layout, and this makes your idea not possible. Alternately, a better idea is to use ItemsControl and RadioButton control.
