### ISSUE TITLE
[Bug] spell error

### ISSUE THREAD

**Issue by emako** [iNKORE-NET/UI.WPF.Modern#95]
https://github.com/iNKORE-NET/UI.WPF.Modern/blob/main/source/iNKORE.UI.WPF.Modern.Controls/Controls/Windows/ContentDialog/ContentDialog.cs#L545

Cound -> Could

**Comment by NotYoojun** [comment]
Okey, the speel eroor is now fixd.

**Comment by emako** [comment]
colleciton -> collection

**Comment by NotYoojun** [comment]
> colleciton -> collection

Dang it! I'll fix later. 😫
